### ISSUE TITLE
Unify outputs from different functions

### ISSUE THREAD

**Issue by sckott** [ropenscilabs/geojsonlint#2]
- [ ] Some return boolean, some character string, move all  to return boolean 
- [ ] On fail, unify outputs. Some return lists, while jsonvalidate returns in attributes - not sure what best method is here for outputs

**Comment by ateucher** [comment]
:+1 for returning boolean

**Comment by sckott** [comment]
@ateucher thoughts on best output on failure?  jsonvalidate returns as data.frame as an attribute, so that the value returned is a boolean, just like when there's no failure, which gives boolean of `TRUE` - this seems to make sense, and make it easy to use this package in others without having to fiddle with it much

**Comment by ateucher** [comment]
I like the simplicity of always returning boolean. Adding the failure output as an attribute makes sense, since it's there if you need it, but doesn't get in the way. Documentation will need to be clear though...

I suppose another way of doing it would be to return a list, where the first position is boolean, and second is the error details:

```r
geojson_validate(bad_geojson)

$valid
[1] FALSE

$errors
      field                             message
1      data no (or more than one) schemas match
2 data.type               must be an enum value
```

But then when it is valid, you're returning a list of length 1 (or second list element is `NULL`), which is sort of annoying...

**Comment by sckott** [comment]
Good idea about returning a list. 

I do think boolean is better. And you're right, we should make sure documentation is clear on that, and gives examples of how to extract that info, combine, etc.
